import  org.junit.jupiter.api.AfterAll;
import  org.junit.jupiter.api.BeforeAll;
import  org.junit.jupiter.api.BeforeEach;
import  org.junit.jupiter.api.Test;
import  org.junit.jupiter.api.Timeout;
import static org.junit.jupiter.api.Assertions.*;
import  java.util.Map;
import  java.util.Arrays;
import  java.util.List;
import static org.evomaster.test.utils.EMTestUtils.*;
import  org.evomaster.client.java.controller.SutHandler;
import  io.restassured.RestAssured;
import static io.restassured.RestAssured.given;
import  io.restassured.response.ValidatableResponse;
import static org.hamcrest.Matchers.*;
import  io.restassured.config.JsonConfig;
import  io.restassured.path.json.config.JsonPathConfig;
import static io.restassured.config.RedirectConfig.redirectConfig;
import static org.evomaster.client.java.controller.contentMatchers.NumberMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.StringMatcher.*;
import static org.evomaster.client.java.controller.contentMatchers.SubStringMatcher.*;




/**
*  This file was automatically generated by EvoMaster on 2025-05-09T18:04:17.743-03:00[America/Buenos_Aires]
 * <br>
*  The generated test suite contains 2 tests
 * <br>
*  Covered targets: 10
 * <br>
*  Used time: 0h 1m 4s
 * <br>
*  Needed budget for current results: 100%
 * <br>
*  This file contains test cases that represent successful calls.
*/
public class EvoMaster_successes_Test {

    
    private static String baseUrlOfSut = "https://petstore3.swagger.io";
    
    
    @BeforeAll
    public static void initClass() {
        RestAssured.enableLoggingOfRequestAndResponseIfValidationFails();
        RestAssured.useRelaxedHTTPSValidation();
        RestAssured.urlEncodingEnabled = false;
        RestAssured.config = RestAssured.config()
            .jsonConfig(JsonConfig.jsonConfig().numberReturnType(JsonPathConfig.NumberReturnType.DOUBLE))
            .redirect(redirectConfig().followRedirects(false));
    }
    
    
    
    
    
    
    
    
    /**
    * Calls:
    * (200) DELETE:/api/v3/store/order/{orderId}
    */
    @Test @Timeout(60)
    public void test_0() throws Exception {
        
        given().accept("*/*")
                .delete(baseUrlOfSut + "/api/v3/store/order/872")
                .then()
                .statusCode(200)
                .assertThat()
                .body(isEmptyOrNullString());
    }
    
    
    /**
    * Calls:
    * (200) POST:/api/v3/pet
    */
    @Test @Timeout(60)
    public void test_1() throws Exception {
        
        given().accept("application/json")
                .contentType("application/x-www-form-urlencoded")
                .body("id=576&name=E75ZZdk69wZ&category=%7B%22id%22%3A262%7D&photoUrls=%5B%5D&tags=%5B%7B%22name%22%3A%22U25iu5U7j%22%7D%2C+%7B%22id%22%3A1690135435%7D%2C+%7B%7D%5D")
                .post(baseUrlOfSut + "/api/v3/pet")
                .then()
                .statusCode(200)
                .assertThat()
                .contentType("application/json")
                .body("'name'", containsString("E75ZZdk69wZ"))
                .body("'photoUrls'.size()", equalTo(0))
                .body("'tags'.size()", equalTo(2));
    }


}
